name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Quality:
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/reusables/quality.yaml

  Release:
    needs: Quality
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/reusables/semantic-release.yaml
